#!/usr/bin/env python3
"""Harness-owned model entrypoint.

Keep this file small:
- generic action receiver
- level dispatch (starts with level 1 stub)
- delegates runtime/CLI/state handling to arc_model_runtime

DO NOT EDIT THIS FILE.
Put component definitions in `components.py` and mechanics/completion logic in
`model_lib.py`.

Later levels inherit prior mechanics by default:
- `init_level_1..init_level_N` run in ascending order
- `apply_level_1..apply_level_N` run in ascending order
- completion inherits from the latest defined `is_level_complete_level_<N>`
So later-level edits in `model_lib.py` should usually add or override only the
current level's hook(s).

Use this file only through its CLI subcommands, for example:
- `python3 model.py status --game-id <game_id>`
- `python3 model.py compare_sequences --game-id <game_id>`
- `python3 model.py exec_file --game-id <game_id> ./play.py`

Do not treat `model.py` like an inline Python REPL or append scratch expressions
to the CLI command.
"""

from __future__ import annotations

import os
from pathlib import Path
import sys

from arcengine import GameAction

# Runtime is supplied by harness in run config tools.
GAME_DIR = Path(__file__).resolve().parent
CONFIG_DIR = Path(str(os.getenv("ARC_CONFIG_DIR", "") or "")).expanduser()
if not str(CONFIG_DIR).strip():
    raise RuntimeError("ARC_CONFIG_DIR is required for model runtime imports.")
RUNTIME_PARENT = CONFIG_DIR / "tools"
if not RUNTIME_PARENT.exists():
    raise RuntimeError(f"model runtime path missing: {RUNTIME_PARENT}")
if str(RUNTIME_PARENT) not in sys.path:
    sys.path.insert(0, str(RUNTIME_PARENT))

from arc_model_runtime import ModelHooks, run_model_cli  # noqa: E402

import model_lib  # noqa: E402


def _iter_level_hooks(prefix: str, level: int):
    for lvl in range(1, int(level) + 1):
        handler = getattr(model_lib, f"{prefix}_{lvl}", None)
        if callable(handler):
            yield lvl, handler


def _latest_level_hook(prefixes: tuple[str, ...], level: int):
    for lvl in range(int(level), 0, -1):
        for prefix in prefixes:
            handler = getattr(model_lib, f"{prefix}_{lvl}", None)
            if callable(handler):
                return handler
    return None


class Hooks(ModelHooks):
    def init_level(self, env, level: int) -> None:
        cfg = model_lib.get_level_config(level)
        env.turn_budget = int(getattr(cfg, "turn_budget", 100))
        env.grid = env.initial_grid_for_level(level)
        used_inherited_hooks = False
        shared_initializer = getattr(model_lib, "init_level_shared", None)
        if callable(shared_initializer):
            shared_initializer(env, int(level), cfg=cfg)
            used_inherited_hooks = True
        for _lvl, initializer in _iter_level_hooks("init_level", int(level)):
            initializer(env, cfg=cfg)
            used_inherited_hooks = True
        if not used_inherited_hooks:
            initializer = getattr(model_lib, "init_level", None)
            if callable(initializer):
                initializer(env, int(level), cfg=cfg)

    def apply_action(
        self,
        env,
        action: GameAction,
        *,
        data: dict | None = None,
        reasoning: str | None = None,
    ) -> None:
        # Generic action receiver (all levels).
        env.turn += 1
        env.turn_budget -= 1
        used_inherited_hooks = False
        shared_applier = getattr(model_lib, "apply_action_shared", None)
        if callable(shared_applier):
            shared_applier(env, action, data=data, reasoning=reasoning)
            used_inherited_hooks = True
        for _lvl, applier in _iter_level_hooks("apply_level", int(env.current_level)):
            applier(env, action, data=data, reasoning=reasoning)
            used_inherited_hooks = True
        if not used_inherited_hooks:
            applier = getattr(model_lib, "apply_action", None)
            if callable(applier):
                applier(env, action, data=data, reasoning=reasoning)

    def is_level_complete(self, env) -> bool:
        # Later levels inherit the latest defined completion rule unless overridden.
        checker = _latest_level_hook(("is_level_complete_level", "is_level_complete"), int(env.current_level))
        if callable(checker):
            return bool(checker(env))
        checker = getattr(model_lib, "is_level_complete", None)
        return bool(checker(env)) if callable(checker) else False


def main() -> int:
    return run_model_cli(Hooks(), game_dir=GAME_DIR)


if __name__ == "__main__":
    raise SystemExit(main())
