"""Level solver entrypoint shared by model and real game.

Run order for solve mode:
1) Dry-run in model:
   python3 "$GAME_DIR/model.py" exec_file "$GAME_DIR/play.py"
2) Real execution:
   arc_repl exec_file "$GAME_DIR/play.py"

This file is a harness-owned static exec_file entrypoint.
DO NOT EDIT THIS FILE.
Put level-specific solve branches and helpers in `play_lib.py`.
"""

import json
from pathlib import Path


try:
    GAME_DIR = Path(__file__).resolve().parent
except NameError:
    GAME_DIR = Path.cwd()


def _is_model(state: dict) -> bool:
    guid = str(state.get("guid", "") or "")
    return guid.startswith("model-") or guid == "model-guid"


def _run_actions(actions):
    for i, action in enumerate(actions, 1):
        frame = env.step(action)
        state_value = frame.state
        if hasattr(state_value, "value"):
            state_value = state_value.value
        levels_completed = frame.levels_completed
        if hasattr(levels_completed, "value"):
            levels_completed = levels_completed.value
        print(
            json.dumps(
                {
                    "step": i,
                    "action": int(action),
                    "state": str(state_value),
                    "current_level": int(levels_completed) + 1,
                }
            )
        )


def _plan_actions(state: dict, level: int) -> list[int]:
    planner = globals().get("plan_level_actions")
    if callable(planner):
        return list(planner(state, level=level))
    return []


def main():
    state = get_state()
    level = int(state.get("current_level", 1))
    mode = "model-dry-run" if _is_model(state) else "real"
    print(json.dumps({"mode": mode, "level": level, "state": state.get("state")}))

    actions = _plan_actions(state, level)
    print(json.dumps({"planned_actions": len(actions), "level": level}))
    _run_actions(actions)


main()
